name: selo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_foreground: assets/app_logo_for.png
  adaptive_icon_background: "#ffffff"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  provider: ^6.1.2
  flutter_localization: ^0.3.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  intl_phone_field: ^3.2.0
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_crashlytics: ^4.3.4
  cloud_firestore: ^5.6.5
  another_flushbar: ^1.12.30
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.3
  intl: ^0.19.0
  shimmer: ^3.0.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  group_button: ^5.3.4
  rename: ^3.0.2
  share_plus: ^10.1.4
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  firebase_app_check: ^0.3.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  intl_utils: ^2.8.10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg_icons/bottom_nav_bar/
    - assets/banners/
    - assets/categories/
    - assets/svg_icons/
    - assets/svg_images/
    - assets/png_images/
    - assets/app_logo.png
    - assets/to_add/
