name: handmadetest_app
description: "A new Flutter project."
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  build_runner: ^2.4.15


  register:
    path: features/register

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true





